package dev.loop.core

import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The contract between the Python server and these models.
 *
 * Fixtures in src/test/resources are generated by tools/gen_fixtures.py, which
 * runs real Instagram-shaped payloads through the real normalisers in
 * loop/instagram.py. If a normaliser changes shape, these tests fail — which is
 * the point. Do not hand-edit the fixtures.
 */
class ContractTest {

    private val json = Json {
        ignoreUnknownKeys = true
        coerceInputValues = true
        explicitNulls = false
    }

    private fun <T> load(name: String, serializer: DeserializationStrategy<T>): T {
        val text = javaClass.classLoader!!.getResourceAsStream(name)!!
            .bufferedReader().readText()
        return json.decodeFromString(serializer, text)
    }

    @Test
    fun `feed decodes every media kind`() {
        val page = load("feed.json", Page.serializer())

        assertEquals("non-media feed entries must be dropped server-side", 3, page.posts.size)
        assertEquals("QVFB_page_two", page.nextMaxId)
        assertTrue(page.hasMore)

        val (photo, carousel, reel) = Triple(page.posts[0], page.posts[1], page.posts[2])

        assertEquals("image", photo.type)
        assertEquals("alice", photo.user.username)
        assertEquals("Beirut, Lebanon", photo.location)
        assertEquals(4321, photo.likeCount)
        assertEquals("evening in @beirut #sunset", photo.caption)
        assertFalse(photo.isCarousel)
        assertNull(photo.video)

        assertEquals("carousel", carousel.type)
        assertTrue(carousel.isCarousel)
        assertEquals(2, carousel.slides.size)
        // The cover of a carousel is its first slide, even when a later one is video.
        assertNull(carousel.video)
        assertNotNull(carousel.slides[1].video)
        assertEquals("", carousel.caption)

        assertEquals("video", reel.type)
        assertTrue(reel.isVideo)
        assertEquals(4500000, reel.viewCount)
        assertTrue(reel.liked)
        assertEquals("Some Song", reel.audio?.title)
        assertEquals("Some Artist", reel.audio?.artist)
    }

    @Test
    fun `media urls are all rewritten through the server`() {
        val page = load("feed.json", Page.serializer())
        val urls = page.posts.flatMap { post ->
            post.slides.flatMap { listOfNotNull(it.image, it.video) } +
                listOfNotNull(post.thumb, post.video, post.user.avatar)
        }.filter { it.isNotEmpty() }

        assertTrue("expected media urls in the fixture", urls.isNotEmpty())
        for (url in urls) {
            assertTrue(
                "a raw CDN url reached the client, which would expose the device IP: $url",
                url.startsWith("/media?"),
            )
        }
    }

    @Test
    fun `aspect ratio is clamped to what Instagram allows`() {
        val page = load("feed.json", Page.serializer())
        val portrait = page.posts[0].slides[0]      // 1080x1350
        assertEquals(0.8f, portrait.aspectRatio, 0.001f)

        assertEquals(1f, Slide(width = 0, height = 0).aspectRatio, 0.001f)
        assertEquals(1.91f, Slide(width = 4000, height = 1000).aspectRatio, 0.001f)
    }

    @Test
    fun `profile decodes counts and the graphql post shape`() {
        val page = load("profile.json", ProfilePage.serializer())

        assertEquals("alice", page.user.username)
        assertEquals(1200000, page.user.counts.followers)
        assertEquals(214, page.user.counts.posts)
        assertTrue(page.user.followsYou)
        assertFalse(page.user.following)
        assertEquals("https://example.com", page.user.externalUrl)
        assertNull("a profile page without more posts reports null", page.nextMaxId)

        // A GraphQL sidecar must normalise to the same Post as a feed carousel.
        assertEquals(1, page.posts.size)
        assertEquals("carousel", page.posts[0].type)
        assertEquals("hi", page.posts[0].caption)
    }

    @Test
    fun `stories decode both photo and video items`() {
        assertEquals(1, load("stories.json", StoryTray.serializer()).tray.size)

        val reel = load("story.json", StoryReel.serializer())
        assertEquals("bob", reel.username)
        assertEquals(2, reel.items.size)

        val photo = reel.items[0]
        assertFalse(photo.isVideo)
        assertNull(photo.video)
        assertEquals("photos fall back to a fixed duration", 5000L, photo.durationMillis)

        val video = reel.items[1]
        assertTrue(video.isVideo)
        assertNotNull(video.video)
        assertEquals(11400L, video.durationMillis)
    }

    @Test
    fun `very short stories are held on screen long enough to see`() {
        assertEquals(2000L, StoryItem(duration = 0.4).durationMillis)
    }

    @Test
    fun `comments decode`() {
        val page = load("comments.json", CommentPage.serializer())
        assertEquals(87, page.count)
        assertEquals(1, page.comments.size)
        val comment = page.comments[0]
        assertEquals("beautiful @alice", comment.text)
        assertEquals("carol", comment.user.username)
        assertEquals(14, comment.likeCount)
        assertTrue(comment.liked)
        // The server omits id and full_name on comment authors; defaults cover it.
        assertEquals("", comment.user.id)
    }

    @Test
    fun `search, activity, health and session decode`() {
        val search = load("search.json", SearchResults.serializer())
        assertEquals("bob", search.users[0].username)
        assertTrue(search.users[0].isPrivate)
        assertEquals(4200000, search.hashtags[0].count)

        val activity = load("activity.json", ActivityFeed.serializer())
        assertTrue(activity.items[0].isNew)
        assertEquals("bob liked your photo.", activity.items[0].text)

        val health = load("health.json", Health.serializer())
        assertTrue(health.instagramReachable)
        assertFalse(health.upstreamProxy)

        val session = load("session.json", SessionState.serializer())
        assertTrue(session.authenticated)
        assertTrue(session.gateRequired)
        assertEquals("alice", session.username)
    }

    @Test
    fun `two factor challenge decodes`() {
        val result = load("two_factor.json", LoginResult.serializer())
        assertTrue(result.needsTwoFactor)
        assertEquals("abc123", result.identifier)
        assertEquals("app", result.method)
    }

    @Test
    fun `unknown fields from a newer server do not break decoding`() {
        val page = json.decodeFromString(
            Page.serializer(),
            """{"posts":[{"id":"1","brand_new_field":42,"slides":[]}],"next_max_id":null}""",
        )
        assertEquals("1", page.posts[0].id)
        assertFalse(page.hasMore)
    }
}
